[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"

[rpc_endpoints]
local-c = "http://localhost:9650/ext/bc/C/rpc"
mysubnet = "http://localhost:9650/ext/bc/mysubnet/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
